variable "tenant_id" {}
variable "subscription_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "object_id" {}
variable "rgname" {}
variable "location" {}
variable "vnetname" {}
variable "websubnetname" {}
variable "appsubnetname" {}
variable "webnsgname" {}
variable "appnsgname" {}
variable "lbpip" {}
variable "lbname" {}
variable "frontend_name" {}
variable "webvmnic" {}
variable "webvmname" {}
variable "appvmnic" {}
variable "appvmname" {}
variable "kvname" {}
variable "vm_admin_username" {}
variable "db_administrator_login_name" {}
variable "sqlsrvname" {}
variable "mysql_sku_name" {}
variable "mysql_version" {}
variable "sqlsrvdbname" {}